INSERT INTO users (name,email,password,isAdmin,phone) VALUES ('test-user','test-email','test-hash',false,'test-phone');
INSERT INTO shop (name, avatar_url, description) VALUES ('test-name', 'test-url', 'test-description');
INSERT INTO users_shop (users_id, shop_id) VALUES (1, 1);
INSERT INTO branch (name, address, type, shop_id,description,site) VALUES ('test-branch', 'test-address', 'online', 1,'','');
INSERT INTO category (name, description, is_unique) VALUES ('test-category', 'test-description', true);
INSERT INTO category_branch (branch_id, category_id) VALUES (1, 1);
INSERT INTO attribute (type, is_value_required, is_unique, name) VALUES ('text', false, false, 'test-attribute');
INSERT INTO product (category_id, status, branch_id, name, price,amount) VALUES
(1, 'stock', 1, 'test-category1',1.0,1),
(1, 'stock', 1, 'test-category2',1.0,1),
(1, 'stock', 1, 'test-category3',1.0,1),
(1, 'stock', 1, 'test-category4',1.0,1),
(1, 'stock', 1, 'test-category5',1.0,1);
UPDATE product SET name = 'not-test-category1' WHERE id = 1;
INSERT INTO log_journal (shop_id, branch_id, product_id, info) VALUES (1, 99, 99, '[{"product_id":1, "name":"test", "timestamp":1, "action":"test-action", "details":"test-details"}]');
INSERT INTO sales (name, date, branch_id, product_id, price, quantity) VALUES
('01.01.24_1', 1704074400, 1, 1, 20, 3), 
('01.01.24_2', 1704078000, 1, 2, 25, 1),
('01.01.24_3', 1704081600, 1, 3, 15, 5),
('02.01.24_1', 1704168000, 1, 4, 5, 10),
('01.02.24_1', 1706760000, 1, 5, 15, 2);
