version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db1
    container_name: db
    ports:
      - 5432:5432
    networks:
    - common-net

  auth: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: go run cmd/sso/main.go
    volumes:
      - "./:/app:ro"
    working_dir: /app
    container_name: auth
    depends_on:
      - db
    ports:
     - 10000:10000
    networks:
    - common-net

  shop: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: go run cmd/shop/main.go
    volumes:
      - "./:/app:ro"
    working_dir: /app
    container_name: shop
    ports:
     - 10001:10001
    networks:
      - common-net

  migrations: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "go run cmd/migrator/main.go --migrations-path=migrations"
    volumes:
      - "./:/app:ro"
    working_dir: /app
    container_name: migrations
    networks:
      - common-net
    depends_on:
      - db
      - shop
      - auth
    networks:
    - common-net
    profiles: [test-shop, test-all]

networks:
  common-net: {}