networks:
  common-net: {}

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db1
    container_name: db
    ports:
      - 5432:5432
    networks:
    - common-net

  auth: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: go run cmd/sso/main.go
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD/backend
    container_name: auth
    depends_on:
      - db
    ports:
     - 10000:10000
    networks:
    - common-net

  shop: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: go run cmd/shop/main.go
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD/backend
    container_name: shop
    ports:
     - 10001:10001
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10001", "describe"]
      interval: 3s
      retries: 5

  template: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "mkdir -p cover &&
      go build -cover -o /app cmd/template/main.go &&
      GOCOVERDIR=cover /app"
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: template
    ports:
     - 10004:10004
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10004", "describe"]
      interval: 3s
      retries: 5

  test: 
    container_name: test
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: go run cmd/migrator/main.go --migrations-path=migrations
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD/backend
    depends_on:
      shop : 
        condition: service_healthy
    networks:
    - common-net

  sso-envoy:
    container_name: "sso-envoy"
    image: envoy/sso:latest
    build:
      context:    ./backend/envoy/sso
    networks:
      - common-net
    ports:
      - "8000:8000"

  ui:
    container_name: "ui"
    image: ui:latest
    networks:
      - common-net
    ports:
      - 3000:80
