networks:
  common-net: {}

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db1
    container_name: db
    ports:
      - 5432:5432
    networks:
    - common-net

  auth: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "mkdir -p cover &&
      go build -cover -o /app cmd/sso/main.go &&
      GOCOVERDIR=cover /app"
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: auth
    depends_on:
      - db
    ports:
     - 10000:10000
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10000", "describe"]
      interval: 10s
      retries: 5
    profiles:
      - auth
      - all

  shop: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "mkdir -p cover &&
      go build -cover -o /app cmd/shop/main.go &&
      GOCOVERDIR=cover /app"
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: shop
    ports:
      - 10001:10001
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10001", "describe"]
      interval: 10s
      retries: 5
    profiles:
      - shop
      - all

  products: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "mkdir -p cover &&
      go build -cover -o /app cmd/products/main.go &&
      GOCOVERDIR=cover /app"
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: products
    ports:
     - 10002:10002
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10002", "describe"]
      interval: 10s
      retries: 5
    profiles:
      - products
      - all

  template: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "mkdir -p cover &&
      go build -cover -o /app cmd/template/main.go &&
      GOCOVERDIR=cover /app"
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: template
    ports:
     - 10004:10004
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10004", "describe"]
      interval: 10s
      retries: 5
    profiles:
      - template
      - all

  branch: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "mkdir -p cover &&
      go build -cover -o /app cmd/branch/main.go &&
      GOCOVERDIR=cover /app"
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: branch
    ports:
     - 10003:10003
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10003", "describe"]
      interval: 10s
      retries: 5
    profiles:
      - branch
      - all

  logs: 
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint: bash -c "mkdir -p cover &&
      go build -cover -o /app cmd/logs/main.go &&
      GOCOVERDIR=cover /app"
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: logs
    ports:
     - 10005:10005
    networks:
      - common-net
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10005", "describe"]
      interval: 10s
      retries: 5
    profiles:
      - logs
      - all

  test:
    container_name: test
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint:  bash -c "
      go run cmd/migrator/main.go --migrations-path=migrations &&
      go run cmd/migrator/main.go --migrations-path=tests/migrations --migrations-table=migrations-test &&
      go test -v ./... " 
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    depends_on:
      shop : 
        condition: service_healthy
      branch : 
        condition: service_healthy
      auth : 
        condition: service_healthy
      logs : 
        condition: service_healthy
      products : 
        condition: service_healthy
    networks:
      - common-net
    profiles:
      - all

  test-shop:
    container_name: test-shop
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint:  bash -c "
      go run cmd/migrator/main.go --migrations-path=migrations &&
      go run cmd/migrator/main.go --migrations-path=tests/migrations --migrations-table=migrations-test &&
      go test -v ./tests/shop/... " 
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    depends_on:
      shop : 
        condition: service_healthy
    networks:
      - common-net
    profiles:
      - shop
  
  test-auth:
    container_name: test-shop
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint:  bash -c "
      go run cmd/migrator/main.go --migrations-path=migrations &&
      go run cmd/migrator/main.go --migrations-path=tests/migrations --migrations-table=migrations-test &&
      go test -v ./tests/sso/... " 
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    depends_on:
      auth : 
        condition: service_healthy
    networks:
      - common-net
    profiles:
      - auth

  test-branch:
    container_name: test-branch
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint:  bash -c "
      go run cmd/migrator/main.go --migrations-path=migrations &&
      go run cmd/migrator/main.go --migrations-path=tests/migrations --migrations-table=migrations-test &&
      go test -v ./tests/branch/... " 
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    depends_on:
      branch : 
        condition: service_healthy
    networks:
      - common-net
    profiles:
      - branch
  
  test-products:
    container_name: test-products
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint:  bash -c "
      go run cmd/migrator/main.go --migrations-path=migrations &&
      go run cmd/migrator/main.go --migrations-path=tests/migrations --migrations-table=migrations-test &&
      go test -v ./tests/products/... " 
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    depends_on:
      products : 
        condition: service_healthy
    networks:
      - common-net
    profiles:
      - products

  test-template:
    container_name: test-template
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint:  bash -c "
      go run cmd/migrator/main.go --migrations-path=migrations &&
      go run cmd/migrator/main.go --migrations-path=tests/migrations --migrations-table=migrations-test &&
      go test -v ./tests/template/... " 
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    depends_on:
      template : 
        condition: service_healthy
    networks:
      - common-net
    profiles:
      - template

  test-logs:
    container_name: test-logs
    image: main-image
    build:
      context:    ./docker
      dockerfile: main-image
    entrypoint:  bash -c "
      go run cmd/migrator/main.go --migrations-path=migrations &&
      go run cmd/migrator/main.go --migrations-path=tests/migrations --migrations-table=migrations-test &&
      go test -v ./tests/logs/... " 
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    depends_on:
      logs : 
        condition: service_healthy
    networks:
      - common-net
    profiles:
      - logs
