// Code generated by mockery v2.52.4. DO NOT EDIT.

package branch_app_test

import (
	context "context"
	proto "pim-sys/gen/go/branch"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// AlterBranch provides a mock function with given fields: ctx, name, branchId, description, address, site
func (_m *Storage) AlterBranch(ctx context.Context, name string, branchId int32, description string, address string, site string) error {
	ret := _m.Called(ctx, name, branchId, description, address, site)

	if len(ret) == 0 {
		panic("no return value specified for AlterBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, string, string, string) error); ok {
		r0 = rf(ctx, name, branchId, description, address, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBranch provides a mock function with given fields: ctx, name, shopID, description, address, site, branch_type
func (_m *Storage) CreateBranch(ctx context.Context, name string, shopID int32, description string, address string, site string, branch_type string) error {
	ret := _m.Called(ctx, name, shopID, description, address, site, branch_type)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, string, string, string, string) error); ok {
		r0 = rf(ctx, name, shopID, description, address, site, branch_type)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBranch provides a mock function with given fields: ctx, branchId
func (_m *Storage) DeleteBranch(ctx context.Context, branchId int32) error {
	ret := _m.Called(ctx, branchId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, branchId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetShopId provides a mock function with given fields: ctx, branchId
func (_m *Storage) GetShopId(ctx context.Context, branchId int32) (int32, error) {
	ret := _m.Called(ctx, branchId)

	if len(ret) == 0 {
		panic("no return value specified for GetShopId")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int32, error)); ok {
		return rf(ctx, branchId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int32); ok {
		r0 = rf(ctx, branchId)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, branchId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBranches provides a mock function with given fields: ctx, shopId
func (_m *Storage) ListBranches(ctx context.Context, shopId int32) ([]*proto.BranchInfo, error) {
	ret := _m.Called(ctx, shopId)

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []*proto.BranchInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]*proto.BranchInfo, error)); ok {
		return rf(ctx, shopId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []*proto.BranchInfo); ok {
		r0 = rf(ctx, shopId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.BranchInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, shopId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListShops provides a mock function with given fields: ctx, userId
func (_m *Storage) ListShops(ctx context.Context, userId int32) ([]int32, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for ListShops")
	}

	var r0 []int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]int32, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []int32); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
