// Code generated by mockery v2.52.4. DO NOT EDIT.

package shop_service_test

import (
	context "context"
	proto "pim-sys/gen/go/shop"

	mock "github.com/stretchr/testify/mock"
)

// Shop is an autogenerated mock type for the Shop type
type Shop struct {
	mock.Mock
}

// AlterShop provides a mock function with given fields: ctx, shopId, name, description, url
func (_m *Shop) AlterShop(ctx context.Context, shopId int32, name string, description string, url string) error {
	ret := _m.Called(ctx, shopId, name, description, url)

	if len(ret) == 0 {
		panic("no return value specified for AlterShop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string, string) error); ok {
		r0 = rf(ctx, shopId, name, description, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteShop provides a mock function with given fields: ctx, shopId
func (_m *Shop) DeleteShop(ctx context.Context, shopId int32) error {
	ret := _m.Called(ctx, shopId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, shopId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListShops provides a mock function with given fields: ctx
func (_m *Shop) ListShops(ctx context.Context) ([]*proto.ShopInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListShops")
	}

	var r0 []*proto.ShopInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*proto.ShopInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*proto.ShopInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.ShopInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShop provides a mock function with given fields: ctx, name, description, url
func (_m *Shop) NewShop(ctx context.Context, name string, description string, url string) error {
	ret := _m.Called(ctx, name, description, url)

	if len(ret) == 0 {
		panic("no return value specified for NewShop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, name, description, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShop creates a new instance of Shop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShop(t interface {
	mock.TestingT
	Cleanup(func())
}) *Shop {
	mock := &Shop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
